server:
  port: 8761

spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
    ip-address: true
  client:
    serviceUrl:
      defaultZone: http://user:123@peer1:8761/eureka
    fetch-registry: true
    register-with-eureka: true

security:
  basic:
    enabled: true # 开启安全配置，也就是需要密码，如果不需要设置为 false 即可, 注意这个参数必须放在application.yml 文件中,不允许放到 bootstrap.yml 文件中
  user:
    name: user
    password: 123 # 在配置了用户名和密码后，我们可以修改地址的访问风格为 curl 风格

