server:
  port: 8901

spring:
  application:
    name: consumer-movice-ribbon

user:
  url: http://localhost:7900/user/

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123@localhost:10000/eureka
  instance:
    prefer-ip-address: true # 在 eureka 中显示 ip

PRODUCER-USER: # 写服务的名称
  ribbon:
    NFLoadBalanceRuleClassName: com.netflix.loadbalancer.RandomRule # 给指定的服务配置负载均衡算法

#ribbon:
#  eureka:
#    enabled: false # 在 eureka 中禁用 ribbon， 禁用后需要自己负载均衡