server:
  port: 7901

spring:
  application:
    name: producer-user

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123@localhost:10000/eureka
  instance:
    prefer-ip-address: true
